import localFont from "next/font/local";
import "./globals.css";
import {Oswald} from "next/font/google";

const oswald = Oswald({
  subsets: ["latin"],
  weight: [ '200', '300', '400', '500', '600', '700'],
  display: "swap",
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${oswald.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
