import localFont from 'next/font/local';
import './globals.css';
import { Oswald, Merriweather } from 'next/font/google';

const oswald = Oswald({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-oswald', // Add this
});

const merriweather = Merriweather({
  subsets: ['latin'],
  weight: ['300', '400', '700', '900'],
  display: 'swap',
  variable: '--font-merriweather', // Add this
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${oswald.variable} ${merriweather.variable} font-oswald antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
